@if (1!=1)
    <option value="Afghanistan">Afghanistan</option>
    <option value="Albania">Albania</option>
    <option value="Algeria">Algeria</option>
    <option value="American Samoa">American Samoa</option>
    <option value="Andorra">Andorra</option>
    <option value="Angola">Angola</option>
    <option value="Anguilla">Anguilla</option>
    <option value="Antartica">Antarctica</option>
    <option value="Antigua and Barbuda">Antigua and Barbuda</option>
    <option value="Argentina">Argentina</option>
    <option value="Armenia">Armenia</option>
    <option value="Aruba">Aruba</option>
    <option value="Australia">Australia</option>
    <option value="Austria">Austria</option>
    <option value="Azerbaijan">Azerbaijan</option>
    <option value="Bahamas">Bahamas</option>
    <option value="Bahrain">Bahrain</option>
    <option value="Bangladesh">Bangladesh</option>
    <option value="Barbados">Barbados</option>
    <option value="Belarus">Belarus</option>
    <option value="Belgium">Belgium</option>
    <option value="Belize">Belize</option>
    <option value="Benin">Benin</option>
    <option value="Bermuda">Bermuda</option>
    <option value="Bhutan">Bhutan</option>
    <option value="Bolivia">Bolivia</option>
    <option value="Bosnia and Herzegowina">Bosnia and Herzegowina</option>
    <option value="Botswana">Botswana</option>
    <option value="Bouvet Island">Bouvet Island</option>
    <option value="Brazil">Brazil</option>
    <option value="British Indian Ocean Territory">British Indian Ocean Territory</option>
    <option value="Brunei Darussalam">Brunei Darussalam</option>
    <option value="Bulgaria">Bulgaria</option>
    <option value="Burkina Faso">Burkina Faso</option>
    <option value="Burundi">Burundi</option>
    <option value="Cambodia">Cambodia</option>
    <option value="Cameroon">Cameroon</option>
    <option value="Canada">Canada</option>
    <option value="Cape Verde">Cape Verde</option>
    <option value="Cayman Islands">Cayman Islands</option>
    <option value="Central African Republic">Central African Republic</option>
    <option value="Chad">Chad</option>
    <option value="Chile">Chile</option>
    <option value="China">China</option>
    <option value="Christmas Island">Christmas Island</option>
    <option value="Cocos Islands">Cocos (Keeling) Islands</option>
    <option value="Colombia">Colombia</option>
    <option value="Comoros">Comoros</option>
    <option value="Congo">Congo</option>
    <option value="Congo">Congo, the Democratic Republic of the</option>
    <option value="Cook Islands">Cook Islands</option>
    <option value="Costa Rica">Costa Rica</option>
    <option value="Cota D'Ivoire">Cote d'Ivoire</option>
    <option value="Croatia">Croatia (Hrvatska)</option>
    <option value="Cuba">Cuba</option>
    <option value="Cyprus">Cyprus</option>
    <option value="Czech Republic">Czech Republic</option>
    <option value="Denmark">Denmark</option>
    <option value="Djibouti">Djibouti</option>
    <option value="Dominica">Dominica</option>
    <option value="Dominican Republic">Dominican Republic</option>
    <option value="East Timor">East Timor</option>
    <option value="Ecuador">Ecuador</option>
    <option value="Egypt">Egypt</option>
    <option value="El Salvador">El Salvador</option>
    <option value="Equatorial Guinea">Equatorial Guinea</option>
    <option value="Eritrea">Eritrea</option>
    <option value="Estonia">Estonia</option>
    <option value="Ethiopia">Ethiopia</option>
    <option value="Falkland Islands">Falkland Islands (Malvinas)</option>
    <option value="Faroe Islands">Faroe Islands</option>
    <option value="Fiji">Fiji</option>
    <option value="Finland">Finland</option>
    <option value="France">France</option>
    <option value="France Metropolitan">France, Metropolitan</option>
    <option value="French Guiana">French Guiana</option>
    <option value="French Polynesia">French Polynesia</option>
    <option value="French Southern Territories">French Southern Territories</option>
    <option value="Gabon">Gabon</option>
    <option value="Gambia">Gambia</option>
    <option value="Georgia">Georgia</option>
    <option value="Germany">Germany</option>
    <option value="Ghana">Ghana</option>
    <option value="Gibraltar">Gibraltar</option>
    <option value="Greece">Greece</option>
    <option value="Greenland">Greenland</option>
    <option value="Grenada">Grenada</option>
    <option value="Guadeloupe">Guadeloupe</option>
    <option value="Guam">Guam</option>
    <option value="Guatemala">Guatemala</option>
    <option value="Guinea">Guinea</option>
    <option value="Guinea-Bissau">Guinea-Bissau</option>
    <option value="Guyana">Guyana</option>
    <option value="Haiti">Haiti</option>
    <option value="Heard and McDonald Islands">Heard and Mc Donald Islands</option>
    <option value="Holy See">Holy See (Vatican City State)</option>
    <option value="Honduras">Honduras</option>
    <option value="Hong Kong">Hong Kong</option>
    <option value="Hungary">Hungary</option>
    <option value="Iceland">Iceland</option>
    <option value="India">India</option>
    <option value="Indonesia">Indonesia</option>
    <option value="Iran">Iran (Islamic Republic of)</option>
    <option value="Iraq">Iraq</option>
    <option value="Ireland">Ireland</option>
    <option value="Israel">Israel</option>
    <option value="Italy">Italy</option>
    <option value="Jamaica">Jamaica</option>
    <option value="Japan">Japan</option>
    <option value="Jordan">Jordan</option>
    <option value="Kazakhstan">Kazakhstan</option>
    <option value="Kenya">Kenya</option>
    <option value="Kiribati">Kiribati</option>
    <option value="Democratic People's Republic of Korea">Korea, Democratic People's Republic of</option>
    <option value="Korea">Korea, Republic of</option>
    <option value="Kuwait">Kuwait</option>
    <option value="Kyrgyzstan">Kyrgyzstan</option>
    <option value="Lao">Lao People's Democratic Republic</option>
    <option value="Latvia">Latvia</option>
    <option value="Lebanon" selected>Lebanon</option>
    <option value="Lesotho">Lesotho</option>
    <option value="Liberia">Liberia</option>
    <option value="Libyan Arab Jamahiriya">Libyan Arab Jamahiriya</option>
    <option value="Liechtenstein">Liechtenstein</option>
    <option value="Lithuania">Lithuania</option>
    <option value="Luxembourg">Luxembourg</option>
    <option value="Macau">Macau</option>
    <option value="Macedonia">Macedonia, The Former Yugoslav Republic of</option>
    <option value="Madagascar">Madagascar</option>
    <option value="Malawi">Malawi</option>
    <option value="Malaysia">Malaysia</option>
    <option value="Maldives">Maldives</option>
    <option value="Mali">Mali</option>
    <option value="Malta">Malta</option>
    <option value="Marshall Islands">Marshall Islands</option>
    <option value="Martinique">Martinique</option>
    <option value="Mauritania">Mauritania</option>
    <option value="Mauritius">Mauritius</option>
    <option value="Mayotte">Mayotte</option>
    <option value="Mexico">Mexico</option>
    <option value="Micronesia">Micronesia, Federated States of</option>
    <option value="Moldova">Moldova, Republic of</option>
    <option value="Monaco">Monaco</option>
    <option value="Mongolia">Mongolia</option>
    <option value="Montserrat">Montserrat</option>
    <option value="Morocco">Morocco</option>
    <option value="Mozambique">Mozambique</option>
    <option value="Myanmar">Myanmar</option>
    <option value="Namibia">Namibia</option>
    <option value="Nauru">Nauru</option>
    <option value="Nepal">Nepal</option>
    <option value="Netherlands">Netherlands</option>
    <option value="Netherlands Antilles">Netherlands Antilles</option>
    <option value="New Caledonia">New Caledonia</option>
    <option value="New Zealand">New Zealand</option>
    <option value="Nicaragua">Nicaragua</option>
    <option value="Niger">Niger</option>
    <option value="Nigeria">Nigeria</option>
    <option value="Niue">Niue</option>
    <option value="Norfolk Island">Norfolk Island</option>
    <option value="Northern Mariana Islands">Northern Mariana Islands</option>
    <option value="Norway">Norway</option>
    <option value="Oman">Oman</option>
    <option value="Pakistan">Pakistan</option>
    <option value="Palau">Palau</option>
    <option value="Panama">Panama</option>
    <option value="Papua New Guinea">Papua New Guinea</option>
    <option value="Paraguay">Paraguay</option>
    <option value="Peru">Peru</option>
    <option value="Philippines">Philippines</option>
    <option value="Pitcairn">Pitcairn</option>
    <option value="Poland">Poland</option>
    <option value="Portugal">Portugal</option>
    <option value="Puerto Rico">Puerto Rico</option>
    <option value="Qatar">Qatar</option>
    <option value="Reunion">Reunion</option>
    <option value="Romania">Romania</option>
    <option value="Russia">Russian Federation</option>
    <option value="Rwanda">Rwanda</option>
    <option value="Saint Kitts and Nevis">Saint Kitts and Nevis</option>
    <option value="Saint LUCIA">Saint LUCIA</option>
    <option value="Saint Vincent">Saint Vincent and the Grenadines</option>
    <option value="Samoa">Samoa</option>
    <option value="San Marino">San Marino</option>
    <option value="Sao Tome and Principe">Sao Tome and Principe</option>
    <option value="Saudi Arabia">Saudi Arabia</option>
    <option value="Senegal">Senegal</option>
    <option value="Seychelles">Seychelles</option>
    <option value="Sierra">Sierra Leone</option>
    <option value="Singapore">Singapore</option>
    <option value="Slovakia">Slovakia (Slovak Republic)</option>
    <option value="Slovenia">Slovenia</option>
    <option value="Solomon Islands">Solomon Islands</option>
    <option value="Somalia">Somalia</option>
    <option value="South Africa">South Africa</option>
    <option value="South Georgia">South Georgia and the South Sandwich Islands</option>
    <option value="Span">Spain</option>
    <option value="SriLanka">Sri Lanka</option>
    <option value="St. Helena">St. Helena</option>
    <option value="St. Pierre and Miguelon">St. Pierre and Miquelon</option>
    <option value="Sudan">Sudan</option>
    <option value="Suriname">Suriname</option>
    <option value="Svalbard">Svalbard and Jan Mayen Islands</option>
    <option value="Swaziland">Swaziland</option>
    <option value="Sweden">Sweden</option>
    <option value="Switzerland">Switzerland</option>
    <option value="Syria">Syrian Arab Republic</option>
    <option value="Taiwan">Taiwan, Province of China</option>
    <option value="Tajikistan">Tajikistan</option>
    <option value="Tanzania">Tanzania, United Republic of</option>
    <option value="Thailand">Thailand</option>
    <option value="Togo">Togo</option>
    <option value="Tokelau">Tokelau</option>
    <option value="Tonga">Tonga</option>
    <option value="Trinidad and Tobago">Trinidad and Tobago</option>
    <option value="Tunisia">Tunisia</option>
    <option value="Turkey">Turkey</option>
    <option value="Turkmenistan">Turkmenistan</option>
    <option value="Turks and Caicos">Turks and Caicos Islands</option>
    <option value="Tuvalu">Tuvalu</option>
    <option value="Uganda">Uganda</option>
    <option value="Ukraine">Ukraine</option>
    <option value="United Arab Emirates">United Arab Emirates</option>
    <option value="United Kingdom">United Kingdom</option>
    <option value="United States">United States</option>
    <option value="United States Minor Outlying Islands">United States Minor Outlying Islands</option>
    <option value="Uruguay">Uruguay</option>
    <option value="Uzbekistan">Uzbekistan</option>
    <option value="Vanuatu">Vanuatu</option>
    <option value="Venezuela">Venezuela</option>
    <option value="Vietnam">Viet Nam</option>
    <option value="Virgin Islands (British)">Virgin Islands (British)</option>
    <option value="Virgin Islands (U.S)">Virgin Islands (U.S.)</option>
    <option value="Wallis and Futana Islands">Wallis and Futuna Islands</option>
    <option value="Western Sahara">Western Sahara</option>
    <option value="Yemen">Yemen</option>
    <option value="Yugoslavia">Yugoslavia</option>
    <option value="Zambia">Zambia</option>
    <option value="Zimbabwe">Zimbabwe</option>
@else
    <option value="France" selected="selected">France </option>

    <option value="Afghanistan">Afghanistan </option>
    <option value="Afrique_Centrale">Afrique_Centrale </option>
    <option value="Afrique_du_sud">Afrique_du_Sud </option>
    <option value="Albanie">Albanie </option>
    <option value="Algerie">Algerie </option>
    <option value="Allemagne">Allemagne </option>
    <option value="Andorre">Andorre </option>
    <option value="Angola">Angola </option>
    <option value="Anguilla">Anguilla </option>
    <option value="Arabie_Saoudite">Arabie_Saoudite </option>
    <option value="Argentine">Argentine </option>
    <option value="Armenie">Armenie </option>
    <option value="Australie">Australie </option>
    <option value="Autriche">Autriche </option>
    <option value="Azerbaidjan">Azerbaidjan </option>

    <option value="Bahamas">Bahamas </option>
    <option value="Bangladesh">Bangladesh </option>
    <option value="Barbade">Barbade </option>
    <option value="Bahrein">Bahrein </option>
    <option value="Belgique">Belgique </option>
    <option value="Belize">Belize </option>
    <option value="Benin">Benin </option>
    <option value="Bermudes">Bermudes </option>
    <option value="Bielorussie">Bielorussie </option>
    <option value="Bolivie">Bolivie </option>
    <option value="Botswana">Botswana </option>
    <option value="Bhoutan">Bhoutan </option>
    <option value="Boznie_Herzegovine">Boznie_Herzegovine </option>
    <option value="Bresil">Bresil </option>
    <option value="Brunei">Brunei </option>
    <option value="Bulgarie">Bulgarie </option>
    <option value="Burkina_Faso">Burkina_Faso </option>
    <option value="Burundi">Burundi </option>

    <option value="Caiman">Caiman </option>
    <option value="Cambodge">Cambodge </option>
    <option value="Cameroun">Cameroun </option>
    <option value="Canada">Canada </option>
    <option value="Canaries">Canaries </option>
    <option value="Cap_vert">Cap_Vert </option>
    <option value="Chili">Chili </option>
    <option value="Chine">Chine </option>
    <option value="Chypre">Chypre </option>
    <option value="Colombie">Colombie </option>
    <option value="Comores">Colombie </option>
    <option value="Congo">Congo </option>
    <option value="Congo_democratique">Congo_democratique </option>
    <option value="Cook">Cook </option>
    <option value="Coree_du_Nord">Coree_du_Nord </option>
    <option value="Coree_du_Sud">Coree_du_Sud </option>
    <option value="Costa_Rica">Costa_Rica </option>
    <option value="Cote_d_Ivoire">Côte_d_Ivoire </option>
    <option value="Croatie">Croatie </option>
    <option value="Cuba">Cuba </option>

    <option value="Danemark">Danemark </option>
    <option value="Djibouti">Djibouti </option>
    <option value="Dominique">Dominique </option>

    <option value="Egypte">Egypte </option>
    <option value="Emirats_Arabes_Unis">Emirats_Arabes_Unis </option>
    <option value="Equateur">Equateur </option>
    <option value="Erythree">Erythree </option>
    <option value="Espagne">Espagne </option>
    <option value="Estonie">Estonie </option>
    <option value="Etats_Unis">Etats_Unis </option>
    <option value="Ethiopie">Ethiopie </option>

    <option value="Falkland">Falkland </option>
    <option value="Feroe">Feroe </option>
    <option value="Fidji">Fidji </option>
    <option value="Finlande">Finlande </option>
    <option value="France">France </option>

    <option value="Gabon">Gabon </option>
    <option value="Gambie">Gambie </option>
    <option value="Georgie">Georgie </option>
    <option value="Ghana">Ghana </option>
    <option value="Gibraltar">Gibraltar </option>
    <option value="Grece">Grece </option>
    <option value="Grenade">Grenade </option>
    <option value="Groenland">Groenland </option>
    <option value="Guadeloupe">Guadeloupe </option>
    <option value="Guam">Guam </option>
    <option value="Guatemala">Guatemala</option>
    <option value="Guernesey">Guernesey </option>
    <option value="Guinee">Guinee </option>
    <option value="Guinee_Bissau">Guinee_Bissau </option>
    <option value="Guinee equatoriale">Guinee_Equatoriale </option>
    <option value="Guyana">Guyana </option>
    <option value="Guyane_Francaise ">Guyane_Francaise </option>

    <option value="Haiti">Haiti </option>
    <option value="Hawaii">Hawaii </option>
    <option value="Honduras">Honduras </option>
    <option value="Hong_Kong">Hong_Kong </option>
    <option value="Hongrie">Hongrie </option>

    <option value="Inde">Inde </option>
    <option value="Indonesie">Indonesie </option>
    <option value="Iran">Iran </option>
    <option value="Iraq">Iraq </option>
    <option value="Irlande">Irlande </option>
    <option value="Islande">Islande </option>
    <option value="Israel">Israel </option>
    <option value="Italie">italie </option>

    <option value="Jamaique">Jamaique </option>
    <option value="Jan Mayen">Jan Mayen </option>
    <option value="Japon">Japon </option>
    <option value="Jersey">Jersey </option>
    <option value="Jordanie">Jordanie </option>

    <option value="Kazakhstan">Kazakhstan </option>
    <option value="Kenya">Kenya </option>
    <option value="Kirghizstan">Kirghizistan </option>
    <option value="Kiribati">Kiribati </option>
    <option value="Koweit">Koweit </option>

    <option value="Laos">Laos </option>
    <option value="Lesotho">Lesotho </option>
    <option value="Lettonie">Lettonie </option>
    <option value="Liban">Liban </option>
    <option value="Liberia">Liberia </option>
    <option value="Liechtenstein">Liechtenstein </option>
    <option value="Lituanie">Lituanie </option>
    <option value="Luxembourg">Luxembourg </option>
    <option value="Lybie">Lybie </option>

    <option value="Macao">Macao </option>
    <option value="Macedoine">Macedoine </option>
    <option value="Madagascar">Madagascar </option>
    <option value="Madère">Madère </option>
    <option value="Malaisie">Malaisie </option>
    <option value="Malawi">Malawi </option>
    <option value="Maldives">Maldives </option>
    <option value="Mali">Mali </option>
    <option value="Malte">Malte </option>
    <option value="Man">Man </option>
    <option value="Mariannes du Nord">Mariannes du Nord </option>
    <option value="Maroc">Maroc </option>
    <option value="Marshall">Marshall </option>
    <option value="Martinique">Martinique </option>
    <option value="Maurice">Maurice </option>
    <option value="Mauritanie">Mauritanie </option>
    <option value="Mayotte">Mayotte </option>
    <option value="Mexique">Mexique </option>
    <option value="Micronesie">Micronesie </option>
    <option value="Midway">Midway </option>
    <option value="Moldavie">Moldavie </option>
    <option value="Monaco">Monaco </option>
    <option value="Mongolie">Mongolie </option>
    <option value="Montserrat">Montserrat </option>
    <option value="Mozambique">Mozambique </option>

    <option value="Namibie">Namibie </option>
    <option value="Nauru">Nauru </option>
    <option value="Nepal">Nepal </option>
    <option value="Nicaragua">Nicaragua </option>
    <option value="Niger">Niger </option>
    <option value="Nigeria">Nigeria </option>
    <option value="Niue">Niue </option>
    <option value="Norfolk">Norfolk </option>
    <option value="Norvege">Norvege </option>
    <option value="Nouvelle_Caledonie">Nouvelle_Caledonie </option>
    <option value="Nouvelle_Zelande">Nouvelle_Zelande </option>

    <option value="Oman">Oman </option>
    <option value="Ouganda">Ouganda </option>
    <option value="Ouzbekistan">Ouzbekistan </option>

    <option value="Pakistan">Pakistan </option>
    <option value="Palau">Palau </option>
    <option value="Palestine">Palestine </option>
    <option value="Panama">Panama </option>
    <option value="Papouasie_Nouvelle_Guinee">Papouasie_Nouvelle_Guinee </option>
    <option value="Paraguay">Paraguay </option>
    <option value="Pays_Bas">Pays_Bas </option>
    <option value="Perou">Perou </option>
    <option value="Philippines">Philippines </option>
    <option value="Pologne">Pologne </option>
    <option value="Polynesie">Polynesie </option>
    <option value="Porto_Rico">Porto_Rico </option>
    <option value="Portugal">Portugal </option>

    <option value="Qatar">Qatar </option>

    <option value="Republique_Dominicaine">Republique_Dominicaine </option>
    <option value="Republique_Tcheque">Republique_Tcheque </option>
    <option value="Reunion">Reunion </option>
    <option value="Roumanie">Roumanie </option>
    <option value="Royaume_Uni">Royaume_Uni </option>
    <option value="Russie">Russie </option>
    <option value="Rwanda">Rwanda </option>

    <option value="Sahara Occidental">Sahara Occidental </option>
    <option value="Sainte_Lucie">Sainte_Lucie </option>
    <option value="Saint_Marin">Saint_Marin </option>
    <option value="Salomon">Salomon </option>
    <option value="Salvador">Salvador </option>
    <option value="Samoa_Occidentales">Samoa_Occidentales</option>
    <option value="Samoa_Americaine">Samoa_Americaine </option>
    <option value="Sao_Tome_et_Principe">Sao_Tome_et_Principe </option>
    <option value="Senegal">Senegal </option>
    <option value="Seychelles">Seychelles </option>
    <option value="Sierra Leone">Sierra Leone </option>
    <option value="Singapour">Singapour </option>
    <option value="Slovaquie">Slovaquie </option>
    <option value="Slovenie">Slovenie</option>
    <option value="Somalie">Somalie </option>
    <option value="Soudan">Soudan </option>
    <option value="Sri_Lanka">Sri_Lanka </option>
    <option value="Suede">Suede </option>
    <option value="Suisse">Suisse </option>
    <option value="Surinam">Surinam </option>
    <option value="Swaziland">Swaziland </option>
    <option value="Syrie">Syrie </option>

    <option value="Tadjikistan">Tadjikistan </option>
    <option value="Taiwan">Taiwan </option>
    <option value="Tonga">Tonga </option>
    <option value="Tanzanie">Tanzanie </option>
    <option value="Tchad">Tchad </option>
    <option value="Thailande">Thailande </option>
    <option value="Tibet">Tibet </option>
    <option value="Timor_Oriental">Timor_Oriental </option>
    <option value="Togo">Togo </option>
    <option value="Trinite_et_Tobago">Trinite_et_Tobago </option>
    <option value="Tristan da cunha">Tristan de cuncha </option>
    <option value="Tunisie">Tunisie </option>
    <option value="Turkmenistan">Turmenistan </option>
    <option value="Turquie">Turquie </option>

    <option value="Ukraine">Ukraine </option>
    <option value="Uruguay">Uruguay </option>

    <option value="Vanuatu">Vanuatu </option>
    <option value="Vatican">Vatican </option>
    <option value="Venezuela">Venezuela </option>
    <option value="Vierges_Americaines">Vierges_Americaines </option>
    <option value="Vierges_Britanniques">Vierges_Britanniques </option>
    <option value="Vietnam">Vietnam </option>

    <option value="Wake">Wake </option>
    <option value="Wallis et Futuma">Wallis et Futuma </option>

    <option value="Yemen">Yemen </option>
    <option value="Yougoslavie">Yougoslavie </option>

    <option value="Zambie">Zambie </option>
    <option value="Zimbabwe">Zimbabwe </option>
    @endif